name: Deploy Develop

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    environment: dev

    env:
      GCP_SA_KEY_PATH: './gcp-key.json'

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/checkout@v2
        with:
          fetch-depth: 20

      - name: Authenticate to GCP
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > $GCP_SA_KEY_PATH
          gcloud auth activate-service-account --key-file $GCP_SA_KEY_PATH

      - name: Install Dependencies
        run: npm ci
      
      - name: Test
        run: npm test

      # Enable after the errors fixed.
      # - name: Eslint
      #   run: npx eslint ./ --ext .js

      - name: Deploy to GCP
        run: npm run deploy:dev
