name: Deploy Develop

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest

    env:
      CLOUDSDK_CORE_PROJECT: 'remessage-dev'
      STAGE: 'dev'
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Authenticate to GCP
        run: gcloud auth activate-service-account --key-file $GCP_SA_KEY

      - name: Install Dependencies
        run: npm ci
      
      - name: Test
        run: npm test

      # Enable after the errors fixed.
      # - name: Eslint
      #   run: npx eslint ./ --ext .js

      - name: Deploy to GCP
        run: npm run deploy:dev
